services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - type: volume
        source: uploads
        target: /data
        volume:
          nocopy: true
    environment:
      DB_HOSTNAME: database
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: ""
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      REDIS_PORT: "6379"
    depends_on:
      - database
      - redis

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums

  redis:
    image: docker.io/valkey/valkey:9@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd

volumes:
  uploads:
