<?php
header('Cache-Control: no-store');
header("Content-Security-Policy: default-src 'none'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");
header('Referrer-Policy: no-referrer');
header('X-Content-Type-Options: nosniff');

try {
    $db = new SQLite3('/var/www/html/db/wallos.db', SQLITE3_OPEN_READONLY);
    $db->busyTimeout(3000);
    $userCount = (int) $db->querySingle('SELECT COUNT(*) FROM user');
    $db->close();
} catch (Throwable $error) {
    http_response_code(503);
    exit('Owner setup is not ready.');
}

if ($userCount > 0) {
    header('Location: /login.php', true, 302);
    exit;
}

$invalid = false;
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    $expected = trim((string) @file_get_contents('/run/wallos/owner-setup.sha256'));
    $presented = $_POST['setup_token'] ?? '';
    $candidate = is_string($presented) ? hash('sha256', $presented) : '';
    if (strlen($expected) === 64 && hash_equals($expected, $candidate)) {
        $forwardedProto = strtolower((string) ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? ''));
        $secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
            $forwardedProto === 'https';
        setcookie('droplive_owner_setup', $expected, [
            'expires' => time() + 3600,
            'path' => '/',
            'secure' => $secure,
            'httponly' => true,
            'samesite' => 'Strict',
        ]);
        header('Location: /registration.php', true, 303);
        exit;
    }
    $invalid = true;
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Claim your Wallos installation</title>
</head>
<body>
  <main>
    <h1>Claim your Wallos installation</h1>
    <p>Enter the one-time owner setup token generated by DropLive.</p>
    <?php if ($invalid): ?>
      <p role="alert">That setup token was not accepted.</p>
    <?php endif; ?>
    <form method="post" action="/droplive-owner-setup.php">
      <label for="setup_token">Owner setup token</label>
      <input id="setup_token" name="setup_token" type="password"
             minlength="32" autocomplete="one-time-code" required autofocus>
      <button type="submit">Continue to owner registration</button>
    </form>
  </main>
</body>
</html>
